#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.onepunchcoder.medium.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default
service nginx restart
