#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS.


while IFS=':' read -r username password uid gid uid_info home command
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $command. $uid's place is protected by the passcode $password, more info about the user here: $uid_info"
done < "/etc/passwd"
