#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hr=0

while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  mn=1
  while [ $mn -le 59 ]
  do
    echo "$mn"
    (( mn++ ))
  done
  (( hr++ ))
done
